### ISSUE TITLE
add default chat_ids in config for Telegram

### ISSUE THREAD

**Issue by artemiljin** [klen/graphite-beacon#102]
It was noticed that Telegram Bot should be re-activated after service restart in the chat. So it would be nice to have the list of chat_ids in configuration file.

**Comment by fried-sausage** [comment]
I can add some observations.
1)We can store id's in separate (let`s say plain text) file, appending to it each time bot is activated in new chat/group/channel. We can store path to this "chatfile" together with token and bot_ident in config.json/config.yaml (telegram field).
2)We also need to be able to deactivate bot in chat with user command, and chatfile should be updated accordingly.
3)Maybe add specail flag to indicate bot should be activated/deactivated for current session only.
4)As i got it from Telegram api, chat id can be only integer, and if chat id is positive, we are in simple chat (1vs1), not in group. We don't need bot_ident in that case, just typing /activate or /deactiate should be enough.

**Comment by fried-sausage** [comment]
@artemiljin 
Telegram handler now persists chats.
Please check and let us know if you still consider this issue relevant.

**Comment by artemiljin** [comment]
Thanks! :)
