### ISSUE TITLE
HipChat handler thoughts HTTPError: HTTP 400: BAD_REQUEST

### ISSUE THREAD

**Issue by schernyshov** [klen/graphite-beacon#103]
Hello guys.

Thanks for your fantastic tool!

However, I couldn't make HipChat notifications work.

Notification fails with error when trying to post message to HipChat.

You can see my config and error logs in attach.

[config.txt](https://github.com/klen/graphite-beacon/files/137879/config.txt)
[errorLog.txt](https://github.com/klen/graphite-beacon/files/137878/errorLog.txt)

**Comment by JC1738** [comment]
Also can't get hipchat to work.  Though I think it was solved with a PR a couple of months back, however I don't think the deliverous/graphite-beacon docker image has been updated.  Can someone please update the latest docker container?

```
[E 160223 00:58:42 concurrent:122] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 212, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/graphite_beacon/handlers/hipchat.py", line 44, in notify
        url=self.options.url, room=self.room, token=self.key), headers={
    AttributeError: 'dict' object has no attribute 'url'
```

**Comment by GarrettHeel** [comment]
@JC1738 I'm not familiar with how deliverous works, but the `Dockerfile` at the root of this repository should be sufficient for you to get the latest release working.

It simply does a `pip install graphite-beacon` which will fetch the latest released. You may want to build cleanly to ensure that this action isn't cached (i.e `docker build -no-cache`)

**Comment by JC1738** [comment]
@GarrettHeel Yes, that route works.  Just letting whoever is maintaining know that deliverous/graphite-beacon that is referenced in the ReadMe is out of date.
