### ISSUE TITLE
PagerDuty integration.

### ISSUE THREAD

**Issue by kwinczek** [klen/graphite-beacon#12]
Would you consider adding PagerDuty integration?

Thanks.

**Comment by ashokrajar** [comment]
This would be a very nice feature to have. Many organizations are depended on PagerDuty for realtime alerting.

**Comment by anitakrueger** [comment]
+1

**Comment by OPpuolitaival** [comment]
I tried couple of ways to do that but for some reason it does not send all failures to the pagerduty. If someone can help to finish that change:

1. try with pygerduty lib: https://github.com/OPpuolitaival/graphite-beacon/tree/pagerduty this send some failures

2. try save way as others are done: https://github.com/OPpuolitaival/graphite-beacon/tree/pagerduty_httpclient this approach send nothing, and does not report any problems

**Comment by Tenzer** [comment]
Can't this issue be closed? It seems like a Pagerduty handler has been added since: https://github.com/klen/graphite-beacon/blob/develop/graphite_beacon/handlers/pagerduty.py.

**Comment by klen** [comment]
Yes, why not?
