### ISSUE TITLE
How can I ignore the None value ?

### ISSUE THREAD

**Issue by jeremywu0127** [klen/graphite-beacon#123]
I have set the `"default_nan_value": -1` and  `"ignore_nan": false` in my config.json, but I still get the None value from the graphite like this `[I 160620 15:31:11 alerts:145] disk usage [graphite.ip-10-0-8-21.df._dev_sda1]: None`, and the `method` is `average`.
Can somebody tell me how to ignore the None value ? thx :)

**Comment by rickymoorhouse** [comment]
What value do you have for 'no_data' - the default for this looks to be critical

On setting this to normal and adjusting my alert settings for normal_handlers this seems to have stopped them for me

**Comment by jeremywu0127** [comment]
it seems that the machine `10.0.8.21` doesn't exist any more, so I got the message like `[I 160620 15:31:11 alerts:145] disk usage [graphite.ip-10-0-8-21.df._dev_sda1]: None`
