### ISSUE TITLE
[BEACON] CRITICAL <CPU> Loading error: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by deltaskelta** [klen/graphite-beacon#150]
I am getting a ton of these emails....It seems to be working sometimes, but then about 60% of the time it gives this alert and cannot reach the service...

here are my alerts. 
```
  "alerts": [
    {
      "name": "Memory",
      "query": "aliasByNode(collectd.*.memory.memory-free, 1)",
      "interval": "10minute",
      "format": "bytes",
      "rules": ["warning: < 100MB", "critical: < 10MB"]
    },

    {
      "name": "Disk Space",
      "query": "aliasByNode(collectd.*.df-root.df_complex-free, 1)",
      "interval": "1hour",
      "format": "bytes",
      "rules": ["warning: < 10GB", "critical: < 5GB"]
    },
```

and the systemd file which runs graphite-beacon looks like this...
```
[Unit]
Description=daemeon for graphite-beacon alerts
After=network.target gunicorn-graphite.service

[Service]
User=graphite
Group=graphite
WorkingDirectory=/home/graphite/graphite-beacon
ExecStart=/home/graphite/env.graphite/bin/graphite-beacon --config=/home/graphite/graphite-beacon/beacon.conf.json --graphite-url=https://user:password@graphite.example.com --logging=error --log_file_prefix=/home/graphite/graphite-beacon/beacon.log --pidfile=/home/graphite/graphite-beacon/beacon.pid

[Install]
WantedBy=multi-user.target
```

If I try going to the urls directly with my browser I get the data so I cannot see why I am getting this error..

    https://user:password@graphite.example.com/render/?target=aliasByNode(collectd.*.memory.memory-free,%201)&from=-10minute&until=-0second&rawData=true

**Comment by garrettheel** [comment]
That looks like a DNS resolution error for the graphite host. You may want to experiment with DNS testing tools (like `dig`) to see if you can reproduce from the host running graphite-beacon

**Comment by deltaskelta** [comment]
Yea, it was an oversight...I cloned the box and repurposed it but forgot I had gb running on a user account, thanks for the input.
