### ISSUE TITLE
Debian wheezy post install script failes due to missing upstart and missing init.d script

### ISSUE THREAD

**Issue by phagedorn** [klen/graphite-beacon#34]
Debian wheezy post install script failes due to missing upstart and missing init.d script :+1: 

Setting up graphite-beacon (0.22.1-4-g616dd3b) ...
/var/lib/dpkg/info/graphite-beacon.postinst: 3: /var/lib/dpkg/info/graphite-beacon.postinst: start: not found
dpkg: error processing graphite-beacon (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 graphite-beacon
E: Sub-process /usr/bin/dpkg returned an error code (1)

Maybe adding a init.d script should help?

**Comment by klen** [comment]
It will be nice. Could you help?

**Comment by klen** [comment]
Thank you for the feedback and request.

**Comment by phagedorn** [comment]
Thanks for merging and add to the package :)
