### ISSUE TITLE
Graphite query returns only ~ 40 records out of hundreds

### ISSUE THREAD

**Issue by joochung** [klen/graphite-beacon#46]
I've configured an alert for filesystem utilization across about a dozen servers. Each server with up to 20-30 filesystems each. When I check the log, it seems the graphite query in graphite-beacon is only returning 40 of the filesystems.

**Comment by joochung** [comment]
When I run the query manually in a browser, I get 788 records returned. But graphite-beacon is only parsing 40 out of the 788.

**Comment by joochung** [comment]
Here is the URL 

http://localhost/render/?target=aliasSub%28server.%2A.%2A.fs.%2A.capacity.PCTused%2C%27%5Eserver%5C.%5B%5E%5C.%5D%2A%5C.%28%5B%5E%5C.%5D%2A%29%5C.fs%5C.%28%5B%5E%5C.%5D%2A%29%5C.capacity%5C.PCTused%27%2C%27%5C1%3A%5C2%27%29&rawData=true&from=-5minute


And here is the query in the config:

	    "query": "aliasSub(server.*.*.fs.*.capacity.PCTused,'^server\\.[^\\.]*\\.([^\\.]*)\\.fs\\.([^\\.]*)\\.capacity\\.PCTused','\\1:\\2')",

**Comment by joochung** [comment]
In my log, it looks like graphite-beacon stops processing additional records after it gets the following message:

[I 150514 16:37:05 core:120] Notify critical:FS PCT Used (5minute):Loading error: 'NoneType' object has no attribute 'get':loading
[D 150514 16:37:05 cli:40] Handler (cli) critical
[E 150514 16:37:05 concurrent:122] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 812, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python2.7/dist-packages/graphite_beacon/alerts.py", line 219, in load
        self.notify('critical', 'Loading error: %s' % e, target='loading', ntype='common')
      File "/usr/local/lib/python2.7/dist-packages/graphite_beacon/alerts.py", line 173, in notify
        return self.reactor.notify(level, self, value, target=target, ntype=ntype, rule=rule)
      File "/usr/local/lib/python2.7/dist-packages/graphite_beacon/core.py", line 126, in notify
        handler.notify(level, alert, value, target=target, ntype=ntype, rule=rule)
      File "/usr/local/lib/python2.7/dist-packages/graphite_beacon/handlers/cli.py", line 49, in notify
        command = self._substituteVariables(self.commandTemplate, level, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/graphite_beacon/handlers/cli.py", line 30, in _substituteVariables
        '${limit_value}': str(kwargs.get('rule', {}).get('value', '')),
    AttributeError: 'NoneType' object has no attribute 'get'

**Comment by kbakulin** [comment]
Such errors happen when no data received for parameter and then CLI handler got `None` in the `rule` parameter.
I fixed it in pull request #50. @joochung, check it.
