### ISSUE TITLE
[Bug] It doesn't work when using the "include " clause in the main configuration file 

### ISSUE THREAD

**Issue by jeremywu0127** [klen/graphite-beacon#65]
hi, I use the "include " clause in the config.json to use other configuration files , but it doesn't work ! The 
beacon only reads the alerts in the last configuration file. 
e.g.
I write the include clause in the config.json like this:
"include": ["adx-test.json", "dsp-test.json"]
but it only reads the "alerts" in the dsp-test.json
so, what can I do when I use the multiple configuration files ?

**Comment by jeremywu0127** [comment]
We have solved this problem , we rewrite the "include_config" function in the core.py. See below:

def include_config(self, config):
        LOGGER.info('Load configuration: %s' % config)
        if config:
            try:
                with open(config) as fconfig:
                    source = COMMENT_RE.sub("", fconfig.read())
                    config = json.loads(source)
                    alerts = config.pop('alerts')
                    self.options['alerts'] += alerts
                    self.options.update(config)
            except (IOError, ValueError):
                LOGGER.error('Invalid config file: %s' % config)

**Comment by GarrettHeel** [comment]
This is fixed in `0.25.3`. Thanks for the bug report!
