### ISSUE TITLE
ubuntu install error

### ISSUE THREAD

**Issue by nancykyo** [klen/graphite-beacon#66]
apt-get install graphite-beacon
Reading package lists... Done
Building dependency tree
Reading state information... Done
graphite-beacon is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 480 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US:",
	LC_ALL = (unset),
	LC_CTYPE = "zh_CN.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Setting up graphite-beacon (0.24.0) ...
root      5555     1  0 Jul15 ?        00:00:00 upstart-udev-bridge --daemon
root      5558     1  0 Jul15 ?        00:00:00 upstart-file-bridge --daemon
root      5561     1  0 Jul15 ?        00:00:00 upstart-socket-bridge --daemon
graphite-beacon start/running, process 22720
root       335     1  0 Jul05 ?        00:00:00 /lib/systemd/systemd-udevd --daemon
root       716     1  0 Jul05 ?        00:00:00 /lib/systemd/systemd-logind
/var/lib/dpkg/info/graphite-beacon.postinst: 4: /var/lib/dpkg/info/graphite-beacon.postinst: systemctl: not found
dpkg: error processing package graphite-beacon (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 graphite-beacon
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by klen** [comment]
Fixed in last version.
