### ISSUE TITLE
update the alert dynamically?

### ISSUE THREAD

**Issue by tpeng** [klen/graphite-beacon#69]
is it possible to update alert rule dynamically without restart the server? looking the code, seems like the `reinit` in core.py is the way to go, but it only get called when catch a `SIGHUP` signal. is it the intended way to do the update?

also, would be nice if it could accept POST request to update specific alert.

**Comment by garrettheel** [comment]
Yep, a SIGHUP is fairly standard as a way of notifying a process that you want it to reload its configuration.

A web API would be nice, but would be a fairly big change and is probably out of scope for now.
