### ISSUE TITLE
Loading error: HTTP 599: Timeout

### ISSUE THREAD

**Issue by lepiklepik** [klen/graphite-beacon#7]
Sometimes i get notification with the 'Loading error: HTTP 599: Timeout' and another one in one minute which tells that everything is ok now. Trying to find the reason of that. Without any success for now.

**Comment by jrgifford** [comment]
@klen being able to ignore timeouts for graphite would be useful. As would being able to increase the tornado concurrent connections, which is related.

**Comment by sursma** [comment]
@klen  It would be great if I can supress these timeout errors.  I keep getting 
 Loading error: HTTP 599: Timeout
then again back to normal
this complete fills my mailbox, cant find real alert
I tried setting
"loading_error": "normal"
still didnt help

**Comment by pzhuk** [comment]
I am getting the same errors, and looking at nginx logs at graphite side - looks like request never had reached graphite. Only small amount of requests are failing from time to time. More looks like a beacon issue with requests expiring in async queue

**Comment by tpeng** [comment]
@pzhuk you could set a longer `request_timeout` (https://github.com/klen/graphite-beacon/blob/develop/graphite_beacon/core.py#L45)

**Comment by okyou** [comment]
'request_timeout': 1200.0,
        'connect_timeout': 1200.0,
still didnt help
lots of Loading error: HTTP 599: Timeout,cant return result when use historical
