### ISSUE TITLE
Receiving emails when its normal

### ISSUE THREAD

**Issue by srinivaskusam** [klen/graphite-beacon#77]
How to avoid this kind of emails alerts

Value: Metrics are loaded

**Comment by VibyJocke** [comment]
In the config file you could set "normal_handlers" to an empty array.

**Comment by garrettheel** [comment]
Yep, explicitly setting `normal_handlers` will stop you getting those. It would be nice if there was a way to subscribe to certain _kinds_ of emails per level, but that's a low priority right now.
