### ISSUE TITLE
Query Interval Question

### ISSUE THREAD

**Issue by sercanaktas** [klen/graphite-beacon#89]
I set the alerts with different intervals (some with 1minute, some 5minute etc), according to the logs beacon queries every 5 second, instead of the query interval I defined.
Is it an intended behavior? How can I change it?

**Comment by mikahanninen** [comment]
I am seeing the same behaviour. Alert interval does not have any impact - queries are done always at 5 second interval.

**Comment by pmartens** [comment]
Met to

**Comment by GarrettHeel** [comment]
Do you have `debug

**Comment by mikahanninen** [comment]
@GarrettHeel : yes I had `"debug": true`. When I turned it to `false`, the query interval was respected. Thanks!

**Comment by sercanaktas** [comment]
@GarrettHeel  Yes, I modified the example config file and left the "debug": true. 
Sadly there were no documentation on the debug flag.

**Comment by GarrettHeel** [comment]
I've since removed the `debug` option from the example configuration files as it's unlikely to be desired behavior. Thanks for the feedback!
