### ISSUE TITLE
Invalid config file

### ISSUE THREAD

**Issue by mikahanninen** [klen/graphite-beacon#90]
I am getting this error always -> [E 151120 13:21:47 core:104] Invalid config file: config.json

I even stripped the config.json into minimum but still get the above error.
{
  "interval": "20minute",
  "logging": "debug",
  "normal_handlers": ["log"],
  "debug": true,
}

--graphite_url is given in the command_line

graphite-beacon version is 0.25.1

**Comment by kwinczek** [comment]
Last object in JSON documents shouldn't have trailing comma. Remove comma from 'debug' line and it should work.

**Comment by mikahanninen** [comment]
Ach... ok my mistake. Thanks :)
