### ISSUE TITLE
returned value none

### ISSUE THREAD

**Issue by crcro** [klen/graphite-beacon#95]
Using graphite-beacon 0.25.3 with latest version of graphite and every checked value is returning none most of the time.
the graphite instance is working well, grafana is drawing graphs correctly.

**Comment by artemiljin** [comment]
I had a bit similar issue. After I checked the url used in request I found that graphite returns me none for some short requested time intervals, so I decided to extend it and got the values. So check the raw URI sent to Graphite.

**Comment by garrettheel** [comment]
Yup, you can inspect the raw data being returned by graphite by appending `&format=raw` to your graphs. There are numerous circumstances where Graphite will return `None` that you may need to work around by changing your graphite configuration or wrapping your query in certain functions.
