### ISSUE TITLE
[telegram] Exceptions if bodies in requested updates doesn't have 'text' key

### ISSUE THREAD

**Issue by artemiljin** [klen/graphite-beacon#99]
handler telegram.py, function
    def _respond_commands(self, update_response):

actually some times bodies which our bot gets doesn't contain text section, so the exception is thrown in this case, which is annoying. I've added
        for update in update_content["result"]:
            if not update["message"].get('text'):
                continue
to avoid it. Need your suggestion if it's OK.

**Comment by GarrettHeel** [comment]
Looks like this has already been fixed in #83. Try the 0.25.3 release

**Comment by artemiljin** [comment]
Thanks! :) Will check.
